USE EMPRESA1

GO	
CREATE VIEW vwInformaçãoProduto
AS
SELECT	e.QTDESTOQUE, 
		p.PRECO, 
		(e.QTDESTOQUE * p.PRECO) as 'Valor Total',
		p.NOMEPRODUTO,
		f.NOMEFORNCEDOR,
		e.DATAVALIDADE
FROM produto p
INNER JOIN FORNECEDOR f
	ON p.CODIGOFORNECEDOR = f.CODIGOFORNECEDOR
INNER JOIN estoque e
	ON e.CODIGOPRODUTO = p.CODIGOPRODUTO;

GO
SELECT * FROM vwInformaçãoProduto; 

-- view - pag38

GO
CREATE VIEW vwRepresentantes
AS
SELECT	r.NOMEREPRESENTANTE,
		f.NOMEFORNCEDOR
FROM FORNECEDOR f
INNER JOIN REPRESENTANTEFORNECEDOR rf
	ON rf.CODIGOFORNECEDOR = f.CODIGOFORNECEDOR
INNER JOIN REPRESENTANTE r
	ON rf.CODIGOREPRESENTANTE = r.CODIGOREPRESENTANTE;

SELECT * FROM vwRepresentantes;	

-- view pag39

GO 
CREATE VIEW vwDetalhesRepresentante
AS
SELECT	r.NOMEREPRESENTANTE,
		f.NOMEFORNCEDOR,
		t.DDD,
		t.TELEFONECLIENTE
FROM FORNECEDOR f
INNER JOIN REPRESENTANTEFORNECEDOR rf
	ON rf.CODIGOFORNECEDOR = f.CODIGOFORNECEDOR
INNER JOIN REPRESENTANTE r
	ON rf.CODIGOREPRESENTANTE = r.CODIGOREPRESENTANTE
INNER JOIN TELEFONE t
	ON t.CODIGOREPRESENTANTE = rf.CODIGOREPRESENTANTE;


SELECT * FROM vwDetalhesRepresentante;

-- view pag40

GO
CREATE VIEW vwClientePedido
AS
SELECT	c.NOMECLIENTE,
		e.NOMEESTADO,
		p.CODIGOPEDIDO,
		p.DATAPEDIDO,
		pr.NOMEPRODUTO
FROM CLIENTE c
INNER JOIN ESTADO e
	ON c.UFCLIENTE = e.UF
INNER JOIN PEDIDO p
	On p.CODIGOCLIENTE = c.CODIGOCLIENTE
INNER JOIN ITENSPEDIDO ip
	ON IP.CODIGOPEDIDO = P.CODIGOPEDIDO
INNER JOIN PRODUTO pr
	on ip.CODIGOPRODUTO = pr.CODIGOPRODUTO;

SELECT * FROM vwClientePedido;


-- view pag41

GO
CREATE VIEW vwClientePedidoFornecedor
AS
SELECT	c.NOMECLIENTE,
		e.NOMEESTADO,
		p.CODIGOPEDIDO,
		p.DATAPEDIDO,
		pr.NOMEPRODUTO,
		f.NOMEFORNCEDOR
FROM CLIENTE c
INNER JOIN ESTADO e
	ON c.UFCLIENTE = e.UF
INNER JOIN PEDIDO p
	On p.CODIGOCLIENTE = c.CODIGOCLIENTE
INNER JOIN ITENSPEDIDO ip
	ON IP.CODIGOPEDIDO = P.CODIGOPEDIDO
INNER JOIN PRODUTO pr
	on ip.CODIGOPRODUTO = pr.CODIGOPRODUTO
INNER JOIN FORNECEDOR f
	ON f.CODIGOFORNECEDOR = pr.CODIGOFORNECEDOR;

SELECT * FROM vwClientePedidoFornecedor;